sesi 1

In [ ]:
print ("Hello")

Hello


In [ ]:
import time


In [ ]:
print(time.ctime())

Thu Feb  6 04:40:57 2025


In [ ]:
x = "hello"
y = 20
c = 30.9
f = ["apple","berry"]

x,y,c,f
print(x,y,c,f)

hello 20 30.9 ['apple', 'berry']


In [ ]:
x = "hello"
y = 20
c = 30.9
f = ["apple","berry"]

x,y,c,f

('hello', 20, 30.9, ['apple', 'berry'])

In [ ]:
o = int(1)
y = int(2.8)
z = int("3")
j = str(20)

print(o,y,z,j)

1 2 3 20


In [ ]:
a = "Hello"
b = " World"
c = a + b
print(c)

Hello World


In [ ]:
a = "Hello World"
print(a[1])

print (len(a) )

e
11


In [ ]:
b = "Binus UNIV"
print (b[2:5])

c = "Binus UNIV"
print (c[:5])

d = "Binus UNIV"
print (b[2:])





nus
Binus
nus UNIV


In [ ]:
 a = "HEllo"
 print(a.upper())

 b = "HEllo"
 print(b.lower())

 c = "Hello"
 print(c.replace("H", "3"))

HELLO
hello
3ello


In [ ]:
 nama = "sam"
x = 19
string = "nama saya {} umur {}"

print (string.format(nama, x))


nama saya sam umur 19


In [ ]:
nama = "Grace"
for i in enumerate(nama) :
  print (i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan (a,b):
  if a>b :
    print("a lebih besar dari b")
  elif a < b :
    print("a kurang dari b")
  else:
    print("a = b")


In [ ]:
perbandingan (4,8)

a kurang dari b


In [ ]:
i = 1
while i<6:
  print(i)
  i += 1


1
2
3
4
5


In [ ]:
i = 1
for i in range (2,6):
  print(i)


2
3
4
5


In [ ]:

for i in range (2,41):
  if i % 2 == 0 :
    print(i , "\ngenap")
  elif i % 2 == 1 :
      print(i , "\nganjil")

2 
genap
3 
ganjil
4 
genap
5 
ganjil
6 
genap
7 
ganjil
8 
genap
9 
ganjil
10 
genap
11 
ganjil
12 
genap
13 
ganjil
14 
genap
15 
ganjil
16 
genap
17 
ganjil
18 
genap
19 
ganjil
20 
genap
21 
ganjil
22 
genap
23 
ganjil
24 
genap
25 
ganjil
26 
genap
27 
ganjil
28 
genap
29 
ganjil
30 
genap
31 
ganjil
32 
genap
33 
ganjil
34 
genap
35 
ganjil
36 
genap
37 
ganjil
38 
genap
39 
ganjil
40 
genap


In [ ]:
import numpy as np


In [ ]:
x = np.array([[1,2,3], [3,6,7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8,2,9], [3,5,7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array([10,9,8,7,5,6])
print("Rata rata :" , np.mean(data))
print("Median :", np.median(data))
print("Standar Deviasi :", np.std(data))
print("Variansi :", np.var(data))
print("Maksimum" , np.max(data))
print("Minimum", np.min(data))


Rata rata : 7.5
Median : 7.5
Standar Deviasi : 1.707825127659933
Variansi : 2.9166666666666665
Maksimum 10
Minimum 5


In [12]:
def calculate(UAS, UTS, ASG):
    return (UAS * 0.5) + (UTS * 0.3) + (ASG * 0.2)

def grading(total):
    if 90 <= total <= 100:
        return "A"
    elif 85 <= total < 90:
        return "A-"
    elif 80 <= total < 85:
        return "B+"
    elif 75 <= total < 80:
        return "B"
    elif 70 <= total < 75:
        return "B-"
    elif 65 <= total < 70:
        return "C"
    elif 60 <= total < 65:
        return "D"
    elif 11 <= total < 60:
        return "E"
    else:
        return "F"

def scores():
    while True:
        try:
            UAS = float(input("Masukkan nilai UAS [0-100]: "))
            if 0 <= UAS <= 100:
                break
            else:
                print("Nilai harus dalam rentang 0 - 100. Coba lagi!")
        except ValueError:
            print("Input harus berupa angka. Coba lagi!")

    while True:
        try:
            UTS = float(input("Masukkan nilai UTS [0-100]: "))
            if 0 <= UTS <= 100:
                break
            else:
                print("Nilai harus dalam rentang 0 - 100. Coba lagi!")
        except ValueError:
            print("Input harus berupa angka. Coba lagi!")

    while True:
        try:
            ASG = float(input("Masukkan nilai ASIGMENT [0-100]: "))
            if 0 <= ASG <= 100:
                break
            else:
                print("Nilai harus dalam rentang 0 - 100. Coba lagi!")
        except ValueError:
            print("Input harus berupa angka. Coba lagi!")

    return UAS, UTS, ASG

def main():
    username = input("Masukkan username: ")
    while True:
        password = input("Masukkan password: ")
        if password == "Admin123":
          print(f"Login Berhasil, Selamat datang {username} ")
          break
        print("Password salah, coba lagi!")

    print("\n")
    nama_mahasiswa = input("Masukkan nama mahasiswa: ")
    UAS, UTS, ASG = scores()

    final_score = calculate(UAS, UTS, ASG)
    grade = grading(final_score)

    print("\n")
    print("============================================")
    print(f"Hasil perolehan nilai {nama_mahasiswa}")
    print(f"Final Score: {final_score:.2f}")
    print(f"Grade: {grade}")
    print("============================================")

if __name__ == "__main__":
    main()


Masukkan username: kimmy
Masukkan password: Admin123
Login Berhasil, Selamat datang kimmy 


Masukkan nama mahasiswa: Kimmy
Masukkan nilai UAS [0-100]: 234
Nilai harus dalam rentang 0 - 100. Coba lagi!
Masukkan nilai UAS [0-100]: 45
Masukkan nilai UTS [0-100]: 22
Masukkan nilai ASIGMENT [0-100]: 1212
Nilai harus dalam rentang 0 - 100. Coba lagi!
Masukkan nilai ASIGMENT [0-100]: 22


Hasil perolehan nilai Kimmy
Final Score: 33.50
Grade: E
